//  ___FILEHEADER___
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import UIKit

// MARK: - Presenter -> View

protocol ___VARIABLE_productName:identifier___ViewInterface: AnyObject {}

// MARK: - View -> Presenter

protocol ___VARIABLE_productName:identifier___PresenterInterface: AnyObject {}

// MARK: - Presenter -> Router

protocol ___VARIABLE_productName:identifier___RouterInterface {}

// MARK: - Presenter -> Interactor

protocol ___VARIABLE_productName:identifier___InteractorInterface {}
