//  ___FILEHEADER___
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import UIKit

class ___VARIABLE_productName:identifier___Presenter {
  // MARK: - Properties

  weak var view: ___VARIABLE_productName:identifier___ViewInterface?
  var interactor: ___VARIABLE_productName:identifier___InteractorInterface?
  var router: ___VARIABLE_productName:identifier___RouterInterface?
}

// MARK: - ___VARIABLE_productName:identifier___PresenterInterface

extension ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___PresenterInterface {}
