//  ___FILEHEADER___
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import Foundation

class ___VARIABLE_productName:identifier___Interactor {
  // MARK: - Properties

  weak var presenter: ___VARIABLE_productName:identifier___PresenterInterface?
}

// MARK: - ___VARIABLE_productName:identifier___InteractorInterface

extension ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___InteractorInterface {}
